# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Approximate Entropy
#' 
#' Calculate the approximate entropy of a time series.
#' 
#' @param x is the time series to analyse
#' @param dim is the embedding dimension of the time series
#' @param R is the radius in which to search for matches
#' @import Rcpp
#' @export
#' 
#' @details Here are some additional details about approximate entropy.
#' 
#' @examples
#' 
#' x = rnorm(1000)
#' 
#' dim = 8
#' R = 0.2
#' 
#' AE = ApproximateEntropy(x, dim, R)
ApproximateEntropy <- function(x, dim, R) {
    .Call(`_NONANr_ApproximateEntropy`, x, dim, R)
}

#' Sample Entropy
#' 
#' Calculate the sample entropy of a time series.
#' 
#' @param x - a single column time series
#' @param m - the length of the vectors to be compared for matches
#' @param R - the radius for accepting matches
#' @import Rcpp
#' @export
#'
#' @details Sample entropy can be used to quantify the complexity of a time series. A higher sample entropy value is associated with a more complex signal (more random). On the other hand a time series with a lower sample entropy value could be considered more predictable and repetitive.
#' 
#' @examples 
#' 
#' x = rnorm(1000)
#' 
#' m = 2
#' R = 0.2
#' 
#' SE = SampleEntropy(x, m, R)
#' 
#' @references
#' Richman, J.S., Moorman, J.R., 2000. Physiological time-series analysis using approximate entropy and sample entropy. Am. J. Physiol. Heart Circ. Physiol. 278. https://doi.org/10.1152/ajpheart.2000.278.6.H2039
SampleEntropy <- function(x, m, R) {
    .Call(`_NONANr_SampleEntropy`, x, m, R)
}

#' Symbolic Entropy 
#' 
#' Calculate the symbolic entropy of a time series.
#' 
#' @param x - A vector of integers
#' @param thresholdVal - the threshold of the search that you want to do
#' @param seqLength - the length of the sequence that you want to find 
#' @import Rcpp
#' @export
#' 
#' @details Like all entropy functions, this one also quantifies the amount of complexity (or uncertainty/unpredictability) in the signal. Symbolic entropy can be used to gather greater insight into the underlying patterns seen in movement data.
#' 
#' @examples 
#' 
#' x = rnorm(1000)
#' 
#' thresholdVal = 2
#' seqLength = 0.2
#' 
#' SymE = SymbolicEntropy(x, thresholdVal, seqLength)
#' 
#' @references
#' Aziz, W., Arif, M. Complexity analysis of stride interval time series by threshold dependent symbolic entropy. Eur J Appl Physiol 98, 30–40 (2006). https://doi.org/10.1007/s00421-006-0226-5
SymbolicEntropy <- function(x, thresholdVal, seqLength) {
    .Call(`_NONANr_SymbolicEntropy`, x, thresholdVal, seqLength)
}

